src/Entity/Devis.php
<?php

namespace App\Entity;

use App\Repository\DevisRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DevisRepository::class)
 */
class Devis
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="devis")
     */
    private $Utilisateur;

    /**
     * @ORM\OneToMany(targetEntity=Tailler::class, mappedBy="Devis")
     */
    private $taillers;

    public function __construct()
    {
        $this->taillers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?User $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    /**
     * @return Collection|Tailler[]
     */
    public function getTaillers(): Collection
    {
        return $this->taillers;
    }

    public function addTailler(Tailler $tailler): self
    {
        if (!$this->taillers->contains($tailler)) {
            $this->taillers[] = $tailler;
            $tailler->setDevis($this);
        }

        return $this;
    }

    public function removeTailler(Tailler $tailler): self
    {
        if ($this->taillers->removeElement($tailler)) {
            // set the owning side to null (unless already changed)
            if ($tailler->getDevis() === $this) {
                $tailler->setDevis(null);
            }
        }

        return $this;
    }
}

src/Controller/DevisController.php
<?php

namespace App\Controller;

use App\Entity\Tailler;
use App\Entity\Haie;
use App\Entity\Devis;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


class DevisController extends AbstractController
{

    #[Route('/devis/liste', name: 'devis_liste')]
    public function listeDevis(Request $request): Response
    { 
        $mesDevis = $this->getDoctrine()
            ->getRepository(Devis::class)
            ->findAll();
        
        return $this->render('devis/liste.html.twig', [
            'controller_name' => 'DevisController',
            'devis'=>$mesDevis,
        ]);
    }

    #[Route('/devis/{id}/delete', name: 'delete_devis', methods: ['GET'])]
    public function deleteDevis(Request $request, Devis $devis, Tailler $tailler): Response
    {
        if ($this->isCsrfTokenValid('delete'.$devis->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($devis);
            $entityManager->flush();

            $tailler = $this->getDoctrine()->getRepository(Tailler::class)->findBy(['id' => $devis->getId()]);
            foreach ($tailler as $key) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($key);
                $entityManager->flush();
            }

        }

        return $this->redirectToRoute('devis_liste', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/devis', name: 'devis')]
    public function index(Request $request): Response
    { 
        $mesHaies = $this->getDoctrine()
            ->getRepository(Haie::class)
            ->findAll();

            // Session initialisation
            $session = new Session();
            if($session->get('kart')){
                $kart = $session->get('kart');
            } else {
                $kart = array();
            }     

        if($request->isMethod('POST')){
            $haie_id = $request->get('haie_select_devis');
            $haie = $this->getDoctrine()->getRepository(Haie::class)->find($haie_id);

            $tailler = new Tailler();
            $tailler->setHauteur($request->get('hauteur'));
            $tailler->setLongueur($request->get('longueur'));
            $tailler->setHaie($haie);

            array_push($kart,$tailler);
            $session->set('kart',$kart);
        }

        $prixTotal= 0;
         foreach ($kart as $product) {
                    if($product->getHauteur() > 1.5) {
                        $prixTotal = $prixTotal + $product->getHaie()->getPrix() * $product->getLongueur()*1.5;
                    } else {
                        $prixTotal = $prixTotal + $product->getHaie()->getPrix() * $product->getLongueur();
                    }
                   
                }
  
        
        return $this->render('devis/index.html.twig', [
            'controller_name' => 'DevisController',
            'haies'=>$mesHaies,
            'taillers'=>$kart,
            'prixT'=>$prixTotal,
        ]);
    }

    #[Route('/devis/remove/{id}', name: 'devis_remove',methods: ['GET'])]
    public function devis_remove(Request $request,string $id): Response
    {
        
        if($request->isMethod('GET')){
            $session = new Session();
            $kart =$session->get('kart'); 
            for ($i=0; $i < count($kart); $i++) { 
                if($i == $id){
                    unset($kart[$i]);
                }
            }
            $kart = array_values($kart);
            $session->remove('kart');
            $session->set('kart',$kart);
            
           
        }  
        return $this->redirectToRoute('devis');  
    }


    #[Route('/devis/validation', name: 'devis_add')]
    public function devis_valid(Request $request,AuthenticationUtils $authenticationUtils): Response
    {

        if ($request->isMethod('POST')){
        $entityManager = $this->getDoctrine()->getManager();
        $date = date("d/m/Y");
        $session = new Session();
        if($session->get('kart')){
            $kart = $session->get('kart');
            $prixT = 0;
            foreach($kart as $haie ){
                if($haie->getHauteur() > 1.5){
                    $prixT = $prixT + $haie->getHaie()->getPrix() * $haie->getLongueur() * 1.5;
                } else {
                    $prixT = $prixT + $haie->getHaie()->getPrix() * $haie->getLongueur();
                }
                     
            }
            if($this->getUser()->getTypeClient()){
                $prixT =  $prixT - $prixT * 0.1;
            }

            $devis = new Devis();
            date_default_timezone_set('Europe/Paris');
            $devis->setDate(new DateTime());
            $devis->setPrix($prixT);
            $devis->setUtilisateur($this->getUser());
            $entityManager->persist($devis);
            $entityManager->flush();
           
            foreach ($kart as $haie) {
                $tailler = new Tailler();
                $tailler->setHauteur($haie->getHauteur());
                $tailler->setLongueur($haie->getLongueur());
                $tailler->setHaie($haie->getHaie());
                $tailler->setDevis($devis);
               
                $entityManager->merge($tailler);
                $entityManager->flush();                   
            }

            $kart = $session->remove('kart');
        } else {
            return $this->redirectToRoute('devis');
        }


        }
        return $this->render('devis/validation.html.twig', [
            'controller_name' => 'Mon devis',
            'haies'=> $kart,
            'prixT'=>$prixT,
            'date'=>$date,
        ]);
    }
}

templates/devis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}P'titJardinier | Devis Panier{% endblock %}

{% block body %}
    <div class="content_ctn_devis">
        <div class="content_ctn__devis">
    <div class="promo_ctn">
        <img src="{{ asset('img/promo.png')}}">
        <h1>           
            {% if app.user.typeclient %}
            Promotion de <span>10%</span> pour les <span>entreprises</span>
            {% else %}
            Aucune promotion pour les particuliers
            {% endif %}
        </h1>
    </div>
     
    <div class="form_devis_ajout_ctn">
   
    {% if is_granted('ROLE_ADMIN') %}
    <div class="optn_line_ctn">
                <a class="optn_btn_link" href="{{ path('devis_liste') }}">
                Administrer les devis
                <img src="{{ asset('img/invoice_see.png')}}">
                </a>  
    </div>
    {% endif %}
        <form action=" {{ path('devis') }}" method="post">
            
            <h1>Ajouter une haie à votre panier !</h1>
            <select name="haie_select_devis" required>
            <option value="" selected disabled>Selectionner votre haie....</option>
            {% for haie in haies %}
               <option value="{{haie.getId()}}">{{haie.getNom()}}</option>
            {% endfor %}
            </select>
            <input type="text" placeholder="Hauteur" name="hauteur" required>
            <input type="text" placeholder="Longueur" name="longueur" required>
            <button class="btn btn-success" type="submit">Ajouter au panier</button>
        </form>
    </div>

</div>
    <div class="devis_cart_ctn ">
        <h2>Panier de {{app.user.prenom}} :</h2>
        <div class="devis_cart">
            {% for tailler in taillers %}
         <div class="cart_row">
                <p>
                
                    <span class="cart_row_name">x1 {{tailler.getHaie().getNom()}}
                        <span class="cart_row_info">
                            ⬌ {{tailler.getLongueur()}}m | ⬍ {{tailler.getHauteur()}}m
                        </span> 
                        
                    </span>
                    <span class="cart_row_prix">
                    {% if tailler.getHauteur() > 1.5 %}
                       {{ tailler.getHaie().getPrix() * tailler.getLongueur() * 1.5 }} 
                     {% else %}
                         {{ tailler.getHaie().getPrix() * tailler.getLongueur() }} 
                    {% endif %}
                    €</span>
                </p>
               
                <a class="link_icon" href="{{ path('devis_remove', {'id': loop.index - 1 }) }}">
                    <img src="{{ asset('img/delete.png')}}">
                </a>
            </div>
            <div class="cart_divider"></div>
         {% else %}
        <div class="cart_row">
               Aucune commande
            </div>
         {% endfor %}
        </div>
        <div class="cart_result">
            <p class="cart_info"> Prix : 
                {% if app.user.typeclient %}
                <strike>{{prixT}}€ </strike>
                (-10%) 
                <span class="cart_prix">{{prixT - (prixT * 0.1)}}€</span>     
                    {% else %}
                    <span class="cart_prix">{{prixT}}€</span>     
                    {% endif %}  
            </p>
        <form action="{{ path('devis_add') }}" method="post">
           <button class="btn btn-success" type="submit" onsubmit="return confirm('Etes-vous sur de vouloir valider de panier ?')">Valider le panier</button>
        </form>
        </div>
    </div>
    </div>

    {% endblock %}

templates/devis/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}P'titJardinier | Liste des devis{% endblock %}

{% block body %}
<div class="content_ctn">
        <div class="optn_line_ctn">
            <a class="optn_btn_link" href="{{ path('devis') }}">
            Retour à la gestion du panier
            <img src="{{ asset('img/arrow.png')}}">
            </a>  
        </div>
        <table id="customclient_table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Utilisateur</th>
                <th style="with:400px">Haie(s)</th>
                <th>Montant</th>
                {# <th>Actions</th> #}
            </tr>
        </thead>
        <tbody>
        {% for devi in devis %}
            <tr class="table_client_line">
                <td>{{ devi.date |date('d-m-Y') }}</td>
                <td>{{devi.utilisateur.username}}</td> 
                <td>
                <details>
            <summary>Voir les haies</summary>
            {% for tailler in devi.taillers %}
                {{tailler.getHaie().getNom}} : ⬌ {{tailler.getLongueur}}m ⬍ {{tailler.Hauteur}}m<br>
            {% endfor %}
            </details>
                </td>
                <td>{{devi.prix}}€</td> 
                 {# <td>
                 <a class="link_icon" href="{{ path('delete_devis', {'id': devi.id}) }}">
                    <img src="{{ asset('img/delete.png')}}">
                </a
                 </td>  #}
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun devis</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

    {% endblock %}

templates/devis/validation.html.twig
{% extends 'base.html.twig' %}

{% block title %}P'titJardinier | Devis Panier{% endblock %}

{% block body %}
<div class="content_ctn_devis">
    <div class="devis_card_ctn mx-auto">
        <div class="devis_card_logo">
            <img src="{{ asset('img/logo_text.png')}}">
        </div>
    <div  class="devis_card_info">
        <span class="float-end">{{app.user.nom}}</span>
        <span class="float-end">{{app.user.prenom}}</span>
        <span class="float-end">{{app.user.adresse}}</span>
        <span class="float-end">{{app.user.cp}}</span><br>
        <span class="float-end">{{app.user.ville}}</span>
    </div>
    <hr>
    <table>
        <thead>
            <tr>
                <th>Haie</th>
                <th>Prix unitaire</th>
                <th>Longueur</th>
                <th>Hauteur</th>
                <th>Prix</th>
            </tr>
        </thead>
        <tbody>
            {% for haie in haies %}
            <tr class="table_client_line">
                <td>{{haie.getHaie.getNom}}</td>
                <td>{{haie.getHaie.getPrix}}</td>
                <td>{{haie.getLongueur}}</td>
                <td>{{haie.getHauteur}}</td>
                {% if haie.getHauteur > 1.5 %}
                    <td>{{ haie.getHaie.getPrix * haie.getLongueur * 1.5}}</td>
                {% else %}
                    <td>{{ haie.getHaie.getPrix * haie.getLongueur }}</td>
                {% endif %}
            </tr>            
    {% endfor %}              
        </tbody>
    </table>
    <hr>
    <div class="devis_result_ctn">
        <div class="date">Créé le : {{date}}</div>
        <div class="price">Prix à payer : {{prixT}} €</div>
    </div>
    
    </div>
</div>

{% endblock %}