src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string")
     */
    private $ville;

    /**
     * @ORM\Column(type="boolean")
     */
    private $typeclient;

    /**
     * @ORM\Column(type="integer")
     */
    private $cp;

    /**
     * @ORM\OneToMany(targetEntity=Devis::class, mappedBy="Utilisateur")
     */
    private $devis;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTypeClient(): ?bool
    {
        return $this->typeclient;
    }

    public function setTypeClient(bool $type_client): self
    {
        $this->typeclient = $type_client;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    /**
     * @return Collection|Devis[]
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): self
    {
        if (!$this->devis->contains($devi)) {
            $this->devis[] = $devi;
            $devi->setUtilisateur($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): self
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getUtilisateur() === $this) {
                $devi->setUtilisateur(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username',TextType::class,array('attr' => ['class'=>'form-control']))
            // ->add('password',PasswordType::class,array('attr' => ['class'=>'form-control']))
            ->add('nom',TextType::class,array('attr' => ['class'=>'form-control']))
            ->add('prenom',TextType::class,array('attr' => ['class'=>'form-control']))
            ->add('adresse',TextType::class,array('attr' => ['class'=>'form-control']))
            ->add('ville',TextType::class,array('attr' => ['class'=>'form-control']))
            ->add('cp',NumberType::class,array('attr' => ['class'=>'form-control']))
            ->add('typeclient',ChoiceType::class,array('attr' => ['class'=>'form-control'],'choices'  => [
                'Entreprise' => true,
                'Particulier' => false,
            ],))
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

#[Route('/client')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository,Request $request): Response
    {
        if($request->get('error') == 1){
            $error = true;
        } else {
            $error = false;
        }
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
            'error' => $error,
        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET','POST'])]
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form, 
            // 'registrationForm' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            try {
                $entityManager->remove($user);
                $entityManager->flush();
                return $this->redirectToRoute('user_index', [
                    'error'=>false,
                ], Response::HTTP_SEE_OTHER);
            } catch (\Throwable $th) {
                return $this->redirectToRoute('user_index', [
                    'error'=>true,
                ], Response::HTTP_SEE_OTHER);
            }
            
        }

        
    }

    #[Route('/', name: 'user_search', methods: ['POST'])]
    public function search(UserRepository $userRepository): Response
    {
        $request = Request::createFromGlobals();
        $user_recherche=$request->get('search_user');
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findBy(['nom' => $user_recherche]),
            'error'=>false,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Etes-vous sur vouloir supprimer ce client ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger mt-2">Supprimer</button>
</form>

templates/user/_form.html.twig
{{ form_start(form, {'attr': {'class': ' form_main'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}P'titJardinier | Modification Client{% endblock %}

{% block body %}
<div class="content_ctn">
    <div class="optn_line_ctn">
        <a class="optn_btn_link" href="{{ path('user_index') }}">
        Retour à la liste des clients
        <img src="{{ asset('img/arrow.png')}}">
        </a>
        
     </div>
     {{ include('user/_form.html.twig') }}
    <div class="delete_line_form">
     {{ include('user/_delete_form.html.twig') }}
    </div>
</div> 
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}P'titJardinier | Les Clients{% endblock %}

{% block body %}
    <div class="content_ctn">
        <div class="optn_line_ctn">
            <a class="optn_btn_link" href="{{ path('app_inscription') }}">
            Ajouter un client
            <img src="{{ asset('img/add.png')}}">
            </a>
            <form action="{{ path('user_search') }}" method="post">
                <input class="input_search" type="search" name="search_user" placeholder="Nom d'un client...">
            </form>
            <a class="home_btn_client" href="{{ path('user_index') }}">
                <img src="{{ asset('img/home.png')}}">
            </a>
        </div>
         {% if error %}
        <div class="alert alert-danger" role="alert">
        Veuillez d'abord supprimer le devis qui correspond au client
        </div>
     {% endif %}
    <table id="customclient_table">
        <thead>
            <tr>
                <th>Nom d'utilisateur</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Cp</th>
                <th>Type du client</th>         
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr class="table_client_line">
                    <td>{{ user.username }}</td>
                    <td>{{ user.nom }}</td>
                    <td>{{ user.prenom }}</td>
                    <td>{{ user.adresse }}</td>
                    <td>{{ user.ville }}</td>
                    <td>{{ user.cp }}</td>
                    <td>{{ user.typeclient ? 'Entreprise' : 'Particulier' }}</td>
                    <td>
                    <a class="link_icon" href="{{ path('user_show', {'id': user.id}) }}">
                            <img src="{{ asset('img/eye.png')}}">
                            </a>
                            <a class="link_icon" href="{{ path('user_edit', {'id': user.id}) }}">
                            <img src="{{ asset('img/editing.png')}}">
                            </a>
                    </td>
                </tr>
                 {% else %}
                  <tr>
                    <td colspan="11">Aucun client trouvé</td>
                </tr> 

            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="content_ctn">
    <div class="show_client_ctn">
    <h1>Détails du client {{user.nom}} {{user.prenom}} <img class="icon" src="{{ asset('img/user.png')}}"></h1>
    <table class="table table-secondary w-75">
        <tbody>
            <tr>
                <th>Nom d'utilisateur :</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Nom :</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prénom :</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse :</th>
                <td>{{ user.adresse }}</td>
            </tr>
            <tr>
                <th>Ville :</th>
                <td>{{ user.ville }}</td>
            </tr>
            <tr>
                <th>Type du client :</th>
                <td>{{ user.typeClient ? 'Entreprise' : 'Particulier' }}</td>
            </tr>
            <tr>
                <th>Code postal :</th>
                <td>{{ user.cp }}</td>
            </tr>
        </tbody>
    </table>
 <div class="d-flex w-50 mx-auto justify-content-around align-items-center mb-4">
       <a class="btn btn-primary mt-2" href="{{ path('user_index') }}">Retour </a>

        <a class="btn btn-success mt-2"href="{{ path('user_edit', {'id': user.id}) }}">Modifier le client</a>

    {{ include('user/_delete_form.html.twig') }}
    </div>
     </div>
     </div>
{% endblock %}